version: '3'

services:
  phpmyadmin:
    container_name: lp1-phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    links:
      - db:db
    ports:
      - "8084:80"
    env_file:
      - .env
    restart: unless-stopped

  db:
    container_name: lp1-mysql
    image: mysql:5.7
    links:
      - db
    env_file:
      - .env
    volumes:
      - "./db/mysql:/var/lib/mysql"
    ports:
      - "3309:3306"
    restart: unless-stopped

  app:
    container_name: lp1-app
    restart: unless-stopped
    image: maven:3-jdk-8-openj9
    working_dir: /app
    links:
      - db:db
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    env_file:
      - .env
    command: mvn clean spring-boot:run
    depends_on:
      - db
